security:
    # Password hashing configuration (esta parte no afecta directamente a la API)
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Empleado
                property: email

    firewalls:
        # Excluir la autenticación para los endpoints de la API
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # API firewall, debe estar sin autenticación
        api:
            pattern: ^/api/
            stateless: true
            # jwt: ~
            # Aquí no debe haber http_basic ni ninguna otra autenticación
            security: false  # Esto desactiva cualquier tipo de seguridad para la API

        # Si tienes otro firewall como 'main', lo dejamos intacto
        main:
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Permite acceso sin autenticación

